# Generated by Django 3.2.14 on 2022-07-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220721_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='father_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='mather_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
