# Generated by Django 3.2.14 on 2022-07-21 18:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220721_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('Parks of being a wallflower', 'Parks of being a wallflower'), ('All the bright places', 'All the bright places'), ('The girl on the train', 'The girl on the train'), ('Django', 'Django')], max_length=78)),
            ],
        ),
    ]
