# Generated by Django 3.2.14 on 2022-07-21 18:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('Arabic', 'اللغة العربية'), ('Maths', 'الرياضيات'), ('English', 'اللغى الانكليزية'), ('French', 'اللغة الفرنسية'), ('biology', 'علم الاحياء'), ('Physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('nationalism', 'التربية القومية'), ('Islamic', 'التربية الاسلامية')], max_length=73)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
