# Generated by Django 3.2.14 on 2022-07-21 19:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220721_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicesub',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اللغة العربية', 'اللغة العربية'), ('Maths', 'الرياضيات'), ('English', 'اللغى الانكليزية'), ('French', 'اللغة الفرنسية'), ('biology', 'علم الاحياء'), ('Physics', 'الفيزياء'), ('chemistry', 'الكيمياء'), ('nationalism', 'التربية القومية'), ('Islamic', 'التربية الاسلامية')], max_length=80),
        ),
    ]
