# Generated by Django 3.2.14 on 2022-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_choicesub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicesub',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
