# Generated by Django 3.2.14 on 2022-07-22 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_subjects_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Arabic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='اللغة العربية_'),
        ),
    ]
