# Generated by Django 3.2.14 on 2022-07-22 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_subjects_arabic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='English',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='اللغة الانكليزية '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='French',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='اللغة الفرنسية '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='Islamic',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='التربية الاسلامية '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='Maths',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='الرياضيات '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='Physics',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='الفيزياء '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='biology',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='علم احياء '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='chemistry',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='الكيمياء '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='father_name',
            field=models.CharField(max_length=200, verbose_name='اسم الاب '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='mather_name',
            field=models.CharField(max_length=200, verbose_name='اسم الام '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='name',
            field=models.CharField(max_length=200, verbose_name='الاسم '),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='nationalism',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='التربية القومية '),
        ),
    ]
