# Generated by Django 3.2.14 on 2022-07-23 00:56

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_choicesub_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceScientific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', multiselectfield.db.fields.MultiSelectField(choices=[('اللغة العربية', 'اللغة العربية'), ('الرياضيات', 'الرياضيات'), ('اللغة الانكليزية', 'اللغة الانكليزية'), ('اللغة الفرنسية', 'اللغة الفرنسية'), ('علم الاحياء', 'علم الاحياء'), ('الفيزياء', 'الفيزياء'), ('الكيمياء', 'الكيمياء'), ('التربية القومية', 'التربية القومية'), ('التربية الاسلامية', 'التربية الاسلامية')], max_length=119, verbose_name='قائمة المواد ')),
                ('number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='رقم الطالب ')),
            ],
        ),
        migrations.CreateModel(
            name='Literary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم ')),
                ('father_name', models.CharField(max_length=200, verbose_name='اسم الاب ')),
                ('mather_name', models.CharField(max_length=200, verbose_name='اسم الام ')),
                ('Arabic', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(600)], verbose_name='اللغة العربية ')),
                ('philosophy', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='فلسفة ')),
                ('English', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='اللغة الانكليزية ')),
                ('French', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='اللغة الفرنسية ')),
                ('history', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='التاريخ ')),
                ('Geography', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='الجغرافيا ')),
                ('nationalism', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='التربية القومية ')),
                ('Islamic', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)], verbose_name='التربية الاسلامية ')),
            ],
        ),
        migrations.RenameModel(
            old_name='ChoiceSub',
            new_name='ChoiceLiterary',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Scientific',
        ),
    ]
