# Generated by Django 3.2.14 on 2022-07-23 00:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20220723_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceliterary',
            name='title',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اللغة العربية', 'اللغة العربية'), ('فلسفة', 'فلسفة'), ('اللغة الانكليزية', 'اللغة الانكليزية'), ('اللغة الفرنسية', 'اللغة الفرنسية'), ('التاريخ', 'التاريخ'), ('الجغرافيا', 'الجغرافيا'), ('التربية القومية', 'التربية القومية'), ('التربية الاسلامية', 'التربية الاسلامية')], max_length=103, verbose_name='قائمة المواد '),
        ),
    ]
