# Generated by Django 3.2.14 on 2022-07-23 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_choiceliterary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='literary',
            name='number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='رقم الطالب '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scientific',
            name='number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='رقم الطالب '),
            preserve_default=False,
        ),
    ]
